<?php
// Dynamically output POI filter mapping as a small JS payload.
header('Content-Type: application/javascript; charset=utf-8');
header('Cache-Control: public, max-age=3600'); // 1 hour cache
header('Vary: Accept-Encoding');

// Enable gzip if client supports it
$gzip_supported = strpos($_SERVER['HTTP_ACCEPT_ENCODING'] ?? '', 'gzip') !== false;
if ($gzip_supported && extension_loaded('zlib')) {
    ob_start('ob_gzhandler');
    header('Content-Encoding: gzip');
}

// Define filter mapping based on OSM tags
// These filters match OSM tag combinations for POI categorization
$filters = [
    'hotel' => [['k'=>'tourism', 'v'=>'hotel']],
    'attraction' => [
        ['k'=>'tourism', 'v'=>'attraction'],
        ['k'=>'waterway', 'v'=>'waterfall'],
        ['k'=>'tourism', 'v'=>'theme_park'],
        ['k'=>'tourism', 'v'=>'museum'],
        ['k'=>'tourism', 'v'=>'viewpoint'],
        ['k'=>'tourism', 'v'=>'zoo'],
        ['k'=>'leisure', 'v'=>'nature_reserve']
    ],
    'tourist_info' => [['k'=>'tourism', 'v'=>'information']],
    'food' => [
        ['k'=>'amenity', 'v'=>'restaurant'],
        ['k'=>'amenity', 'v'=>'biergarten'],
        ['k'=>'amenity', 'v'=>'fast_food'],
        ['k'=>'amenity', 'v'=>'food_court'],
        ['k'=>'shop', 'v'=>'bakery'],
        ['k'=>'amenity', 'v'=>'cafe']
    ],
    'nightlife' => [
        ['k'=>'amenity', 'v'=>'bar'],
        ['k'=>'amenity', 'v'=>'pub'],
        ['k'=>'amenity', 'v'=>'nightclub']
    ],
    'gas_stations' => [
        ['k'=>'amenity', 'v'=>'fuel']
    ],
    'charging_station' => [
        ['k'=>'amenity', 'v'=>'charging_station']
    ],
    'parking' => [
        ['k'=>'amenity', 'v'=>'parking'],
        ['k'=>'amenity', 'v'=>'parking_entrance'],
        ['k'=>'amenity', 'v'=>'parking_space']
    ],
    'bank' => [
        ['k'=>'amenity', 'v'=>'bank'],
        ['k'=>'amenity', 'v'=>'atm']
    ],
    'healthcare' => [
        ['k'=>'amenity', 'v'=>'hospital'],
        ['k'=>'amenity', 'v'=>'pharmacy']
    ],
    'fitness' => [
        ['k'=>'leisure', 'v'=>'sports_hall'],
        ['k'=>'leisure', 'v'=>'sports_centre'],
        ['k'=>'leisure', 'v'=>'fitness_station'],
        ['k'=>'leisure', 'v'=>'fitness_centre']
    ],
    'laundry' => [['k'=>'shop', 'v'=>'laundry']],
    'supermarket' => [
        ['k'=>'shop', 'v'=>'supermarket'],
        ['k'=>'shop', 'v'=>'mall'],
        ['k'=>'shop', 'v'=>'department_store']
    ],
    'tobacco' => [['k'=>'shop', 'v'=>'tobacco']],
    'cannabis' => [['k'=>'shop', 'v'=>'cannabis']],
    'transport' => [
        ['k'=>'public_transport', 'v'=>'stop_position'],
        ['k'=>'public_transport', 'v'=>'station']
    ],
    'dump_station' => [['k'=>'amenity', 'v'=>'sanitary_dump_station']],
    'campgrounds' => [
        ['k'=>'tourism', 'v'=>'caravan_site'],
        ['k'=>'tourism', 'v'=>'camp_site']
    ]
    ,
    'natureparks' => [
        ['k'=>'leisure', 'v'=>'park'],
        ['k'=>'leisure', 'v'=>'nature_reserve'],
        ['k'=>'natural', 'v'=>'nature_reserve']
    ]
];

echo "// Auto-generated POI filters (generated by php)\n";
echo "window.POI_FILTERS = ";
echo json_encode($filters, JSON_UNESCAPED_UNICODE);
echo ";\n";

// Also expose the allowed categories list (filtered by user permissions if needed)
$allowed = [];
if (function_exists('get_poi_categories')) {
    $allKeys = (array) get_poi_categories();
} else {
    $allKeys = array_keys($filters);
}
foreach ($allKeys as $k) {
    if (!function_exists('has_category_permission') || has_category_permission($k)) {
        $allowed[] = $k;
    }
}
echo "// POI categories allowed for current user\n";
echo "window.POI_ALLOWED_CATEGORIES = ";
echo json_encode($allowed, JSON_UNESCAPED_UNICODE);
echo ";\n";

// Also expose a small marker that indicates this payload is server-generated
echo "window.POI_FILTERS_GENERATED = true;\n";

// Flush gzip buffer if enabled
if ($gzip_supported && extension_loaded('zlib')) {
    ob_end_flush();
}
?>
